"""empty message

Revision ID: 0b1b1ae2ec02
Revises: 6dec40e3124a
Create Date: 2020-05-11 19:23:32.597748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1b1ae2ec02'
down_revision = '6dec40e3124a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vk_public', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vk_public', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vk_public', type_='foreignkey')
    op.drop_column('vk_public', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
