"""empty message

Revision ID: 767216cafad3
Revises: 
Create Date: 2020-05-04 00:33:24.826513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767216cafad3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.Integer(), nullable=True),
    sa.Column('data_json', sa.String(length=10000), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_date'), 'post', ['date'], unique=False)
    op.create_table('vk_public',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('bot_token', sa.String(length=200), nullable=True),
    sa.Column('tg_channel', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vk_public')
    op.drop_index(op.f('ix_post_date'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
